#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive DEBCONF_NOWARNINGS=yes
sudo apt-get update -qq && sudo apt-get DEBIAN_FRONTEND=noninteractive DEBCONF_NOWARNINGS=yes install -yqq --no-install-recommends \
  genisoimage libfuse2
[[ -f pyproject.toml ]] && uv sync --frozen || true
